apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-prod-in-prod
  annotations:
    policy.open-cluster-management.io/standards: NIST 800-53
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/controls: CM-2 Baseline Configuration
spec:
  remediationAction: inform
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-prevent-prod-not-in-prod
        spec:
          remediationAction: inform
          severity: low
          namespaceSelector:
            include:
              - default
          object-templates:
            - complianceType: mustNothave
              objectDefinition:
                apiVersion: v1
                kind: Pod
                metadata:
                  labels:
                    phase: prod
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-deployment
placementRef:
  name: placement-policy-deployment
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: policy-deployment
  kind: Policy
  apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-deployment
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: environment, operator: NotIn, values: ["prod"]}
